name: Release Based on Target Branch

on:
  workflow_dispatch:
    inputs:
      platform_backend_version:
        description: 'Platform backend version to use, if releasing.'
        required: false
        default: ''
      platform_backend_release_type:
        description: 'Platform backend: Omit for standard releases, "bounce" for a restart, "rollback" to move backwards'
        required: false
        default: ''
      platform_frontend_version:
        description: 'Platform frontend version to use, if releasing.'
        required: false
        default: ''
      platform_frontend_release_type:
        description: 'Platform frontend: Omit for standard releases, "bounce" for a restart, "rollback" to move backwards'
        required: false
        default: ''
      hydra_version:
        description: 'Hydra version to use, if releasing.'
        required: false
        default: ''
      hydra_release_type:
        description: 'Hydra: Omit for standard releases, "bounce" for a restart, "rollback" to move backwards'
        required: false
        default: ''
      strelka_version:
        description: 'Strelka version to use, if releasing.'
        required: false
        default: ''
      strelka_release_type:
        description: 'Strelka: Omit for standard releases, "bounce" for a restart, "rollback" to move backwards'
        required: false
        default: ''

jobs:
  update-files:
    runs-on: ubuntu-20.04

    environment: all
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Configure AWS credentials (Static Account)
      uses: aws-actions/configure-aws-credentials@v1.6.0
      continue-on-error: true
      with:
        # Use a role instead of including credentials in secrets, and keep the role in secrets just for gating.
        role-to-assume: ${{ secrets.ECR_REPO_ROLE }}
        role-duration-seconds: 7200 # 2 hours
        aws-region: us-east-1

    - name: 2nd Attempt Configure AWS credentials (Static Account)
      uses: aws-actions/configure-aws-credentials@v1.6.0
      if: ${{ env.AWS_ACCESS_KEY_ID == '' }}
      with:
        # Use a role instead of including credentials in secrets, and keep the role in secrets just for gating.
        role-to-assume: ${{ secrets.ECR_REPO_ROLE }}
        role-duration-seconds: 7200 # 2 hours
        aws-region: us-east-1

    - name: Update files
      run: |
        platform_backend_version=${{ github.event.inputs.platform_backend_version }}
        platform_frontend_version=${{ github.event.inputs.platform_frontend_version }}
        hydra_version=${{ github.event.inputs.hydra_version }}
        strelka_version=${{ github.event.inputs.strelka_version }}
        
        platform_backend_version=${platform_backend_version#v}
        platform_frontend_version=${platform_frontend_version#v}
        hydra_version=${hydra_version#v}
        strelka_version=${strelka_version#v}

        echo "platform_backend_version: $platform_backend_version (${{ github.event.inputs.platform_backend_version }})"
        echo "platform_backend_release_type: ${{ github.event.inputs.platform_backend_release_type }}"
        echo "platform_frontend_version: $platform_frontend_version (${{ github.event.inputs.platform_frontend_version }})"
        echo "platform_frontend_release_type: ${{ github.event.inputs.platform_frontend_release_type }}"
        echo "hydra_version: $hydra_version (${{ github.event.inputs.hydra_version }})"
        echo "hydra_release_type: ${{ github.event.inputs.hydra_release_type }}"
        echo "strelka_version: $strelka_version (${{ github.event.inputs.strelka_version }})"
        echo "strelka_release_type: ${{ github.event.inputs.strelka_release_type }}"
        echo "Branch: "${GITHUB_REF##*/}

        git config --global user.name 'Sublime Release Bot'
        git config --global user.email 'hello@sublimesecurity.com'

        should_update=""
        if [ "$platform_backend_version" != "" ]; then
          .github/workflows/validate_and_update_service.sh "Platform BE" "bora-eu-west-1.json" "bora-lite" "14" "bora*.json mantis*.json" "$platform_backend_version" "${{ github.event.inputs.platform_backend_release_type }}"
          should_update="true"
        fi

        if [ "$platform_frontend_version" != "" ]; then
          .github/workflows/validate_and_update_service.sh "Platform FE" "dashboard-eu-west-1.json" "dashboard" "7" "dashboard*.json" "$platform_frontend_version" "${{ github.event.inputs.platform_frontend_release_type }}"
          should_update="true"
        fi

        if [ "$strelka_version" != "" ]; then
          .github/workflows/validate_and_update_service.sh "Strelka" "strelka-eu-west-1.json" "strelka-backend" "18" "strelka*.json" "$strelka_version" "${{ github.event.inputs.strelka_release_type }}"
          should_update="true"
        fi

        if [ "$hydra_version" != "" ]; then
          .github/workflows/validate_and_update_service.sh "Hydra" "hydra-eu-west-1.json" "hydra" "6" "hydra*.json" "$hydra_version" "${{ github.event.inputs.hydra_release_type }}"
          should_update="true"
        fi

        if [ "$should_update" == "true" ]; then
          commit_message=$(sed 's/.*/& +/' release-commit-msg.txt |  sed ':a;{N;s/\n/ /;ba}')
          commit_message=${commit_message::-2}

          allow_empty_option=""
          if test -f "allow_empty"; then
            allow_empty_option="--allow-empty"
          fi

          git commit $allow_empty_option -m "$commit_message"
          git push origin ${GITHUB_REF##*/}
        else
          # Doesn't need to be a failure, but this was success means it actually did something.
          echo "Neither target included an actionable update. Failing"
        fi
        

    - name: Get the head ref (eg branch)
      id: get_head
      run: echo "##[set-output name=MESSAGE;]$(git log -1 --pretty=format:"%s")"

    # https://github.com/marketplace/actions/webhook-action is more flexible if needed
    - name: Invoke Deployment Notification Hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_type: 'json-extended'
        webhook_url: ${{ secrets.PLATFORM_RELEASE_WEBHOOK }}
        webhook_secret: "foobar"
        data: '{ "is_promotion": "false", "message": "${{ steps.get_head.outputs.MESSAGE }}" }'
